spring.application.name=GestionAmbientes

spring.datasource.url=jdbc:mysql://localhost:5432/GestionAmbientes
spring.datasource.username=root
spring.datasource.password=Lalaloopsy1!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true